<?php
if ($test || $rid == 1168) {
    $test = true;
    //require_once($_SERVER['DOCUMENT_ROOT'] . '/lib/stripe-test-config.php');
}// else require_once($_SERVER['DOCUMENT_ROOT'] . '/lib/stripe-config.php');
  
$header_setting['no_nav']=true;
require($_SERVER['DOCUMENT_ROOT'].'/mod/header.php');
?>
<style>
h1 {
    font-size:72px;
    line-height:.95;
}
p {
    line-height:1.1;
    font-size:18px;
}
li {
    font-size:18px;
}
.letter {
    padding:55px;
    width:750px;
    margin:auto;
    box-shadow: 0 0 0 1px rgba(var(--rgb-black), 0.05),0 1px 0 0 rgba(var(--rgb-black), 0.05),0 10px 40px -20px rgba(var(--rgb-black), 0.25),0 20px 60px -25px rgba(var(--rgb-black), 0.2),0 20px 20px -30px rgba(var(--rgb-black), 0.15),0 40px 30px -40px rgba(var(--rgb-black), 0.25),0 60px 40px -50px rgba(var(--rgb-black), 0.3);
    color:rgba(var(--rgb-black), .8)
}
</style>
<div class="space4"></div>
<div class="container" style='width:850px;margin:auto;'>
<h3><strong>TERMS OF SERVICE (revisit for consultants and academy)</strong></h3>
<p><strong>1. Fees & Payments Policy</strong></p>
<p><i>1.1. Fees for our Product.</i> You agree to pay <u>Readitfor.me</u> LLC and its subsidiary products any fees for each Product you purchase or use in accordance with the pricing and payment terms presented to you for that Product. We use third party payment processors (Stripe and PayPal) to bill you through a payment account linked to your <u>Readitfor.me</u> LLC and its subsidiary products  account(s). The processing of payments will be subject to the terms, conditions and privacy policies of the applicable payment processor, in addition to this Agreement. Where applicable, you will be billed using the billing method you select through your account management page. If you have elected to pay the fees by credit card, you represent and warrant that the credit card information you provide is correct and you will promptly notify <u>Readitfor.me</u> LLC and its subsidiary products of any changes to such information. Fees paid by you are non-refundable, except as provided in these Terms or when required by law. Included in your fee may be technical support in respect of the Product and it is only provided to <u>Readitfor.me</u> LLC and its subsidiary products  customers. <u>Readitfor.me</u> LLC and its subsidiary products’ support agents are not trained in custom-coding and technical support for any custom-coding is the responsibility of the customer and <u>Readitfor.me</u> LLC and its subsidiary products’ accepts no responsibility to provide such support. Unless otherwise indicated, all fees and other charges are in U.S. dollars, and all payments shall be in U.S. currency. In no event will <u>Readitfor.me</u> LLC and its subsidiary products  credit, refund, or reimburse you for a foreign exchange fee charged by your credit card or for any difference in fees due to currency conversion.</p>
<p><i>1.2. Recurring Subscriptions.</i> Our Product is billed on a subscription basis (“Subscriptions”). This means that you will be billed in advance on a recurring, periodic basis (each period is called a “billing cycle”). Billing cycles are typically monthly or annual, depending on what subscription plan you select when purchasing a Subscription. However, due to the value being delivered upfront, all monthly billing cycles are on an annual term, unless explicitly expressed otherwise. Payment will be charged to your chosen payment method at confirmation of purchase and at the start of every new billing cycle. Your Subscription will automatically renew at the end of each term unless you cancel your account through your online account management page or by contacting us at support@<u>Readitfor.me</u> at least one business day before the end of the term. While we will never want to lose a customer, you may cancel auto-renewal on your Subscription at any time, in which case your Subscription will continue until the end of that term before terminating. </p>
<p>If you initially sign up for a plan that includes a free or discounted trial period, and you do not cancel that account before the stated trial period expires, you will be billed for the full price of the plan starting on the day the trial period ends. If you cancel prior to the processing of your first payment following the trial period, you will not be charged.</p>
<p><u>Readitfor.me</u> LLC and its subsidiary products may change the price for Subscriptions from time to time and will communicate any price changes to You in advance and, if applicable, how to accept those changes. Price changes for Subscriptions will take effect at the start of the next subscription period following the date of the price change. As permitted by local law, You accept the new price by continuing to use Your Subscription after the price change takes effect. If You do not agree with the price changes, You have the right to reject the change by cancelling Your Subscription before the price change goes into effect on your next renewal. Please therefore make sure you read any such notification of price changes carefully.</p>
<p>We, through our third-party providers (Stripe and PayPal) will keep your detailed payment information, such as non-sensitive credit card partial numbers and expiration date, on file. We do not access this information, except through provided programmatic methods by the provider(s). You are responsible for keeping your payment details up-to-date by changing the details in your account settings.  When your details change or are due to expire, we may obtain or receive from your payment provider updated payment details, including your card number, expiration date, and CVV (or equivalent). This enables us to provide you access to the Product.  You authorize us to continue to charge your credit card using the updated information.  If a payment is not successfully authorized due to expiration, insufficient funds, or otherwise, we may suspend or terminate your subscription until applicable changes have occurred. You also agree that we may charge you via your payment method on file if you elect to restart your subscription.</p>
<p>Any change (including any upgrade, downgrade or other modification) to any plan by you in a trial period will end the trial immediately. You will be billed for your first term period (i.e. the first annual or monthly period) immediately upon upgrading. For any upgrade or downgrade in plan level after any trial period, your credit, debit, or other payment card will automatically be charged the new rate on your next billing cycle. You will be billed immediately for the prorated difference for the current billing cycle for any upgrade to any higher priced plan during that billing cycle. If a plan downgrade causes a credit to your account, this credit will be used toward your next billing cycle(s). This credit will not be refunded.</p>
<p><i>1.3 Lifetime Memberships.</i> Lifetime subscriptions are for the lifetime of the purchased product. While unanticipated, a product may no longer warrant support and may be eliminated from our product set. Lifetime subscriptions can be refunded within the first seventy-two (72) hours after payment has been received. After that point they are non-refundable. If the Lifetime Offer was purchased using a multi-payment plan, the refund must be requested within seventy-two (72) hours of the first payment. After this period no refunds will be provided, and you are obligated to make all future payments on the payment plan, regardless of your level of product usage or satisfaction. If you cancel any Lifetime offer within seventy-two (72) hours of the original purchase, you will lose access to such service.</p>
<p>Lifetime Consultants: Lifetime consultant subscriptions provide an individual customer continued access to the Simple Consultant program and to all current and future programs issued by <u>Readitfor.me</u>, Simple, or any other <u>Readitfor.me</u> brand.</p>
<p><i>1.4. Taxes.</i> Our prices listed do not include any taxes, levies, duties or similar governmental assessments of any nature such as value-added, sales, use, or withholding taxes, assessable by any jurisdiction (collectively, “Taxes”) unless otherwise indicated. You are responsible for paying Taxes associated with your purchase and keeping your billing information up to date.</p>
<p>(a)  United States Sales Tax. If we have a legal obligation to pay or collect sales tax for which you are responsible, we will calculate the sales tax based upon the billing information we have about you and charge you that amount (which, if your billing information is incomplete or inaccurate, may be the highest prevailing rate then in effect), unless you provide us with a valid tax exemption certificate acceptable to the appropriate taxing authority.  If you provide us with a tax exemption certificate, you represent and warrant that it accurately reflects your tax status and that you will keep such document current and accurate. If we subsequently determine in our sole discretion that your tax exemption document is valid, we will refund the sales tax collected.</p>
<p>(b) Non-United States Sales Tax. If applicable, we will charge you VAT, GST, or any other sales, consumption or use taxes that arise in connection with your purchases of our Product unless you provide us with a tax identification number that entitles you to an exemption, a valid tax exemption certificate or other documentary proof issued by an appropriate taxing authority that tax should not be charged. If you are located in a jurisdiction with multiple sales, consumption, or use taxes, we may charge you the highest prevailing rate if your billing information is incomplete or inaccurate.  If you are required by law to withhold any Taxes from your payments to <u>Readitfor.me</u> LLC and its subsidiary products, you must provide <u>Readitfor.me</u> LLC and its subsidiary products with an official tax receipt or other appropriate documentation to support such payments.</p>
<p><i>1.5. Price Changes.</i> <u>Readitfor.me</u> LLC and its subsidiary products may change the fees charged to you for the Services at any time, provided that, for Product billed on a subscription basis, the change will become effective only at the end of the then-current term of your Subscription. <u>Readitfor.me</u> LLC and its subsidiary products will provide you with advance notice of any change in fees and you will have the opportunity to cancel your Subscription as set forth in Section 1.2.</p>
<p><i>1.6  Refund Policy.</i>  We provide a full no-questions-asked refund within seventy-two (72) hours of first signing-up with <u>Readitfor.me</u> LLC and its subsidiary products. To request a refund for these products, simply send us an email to support@<u>Readitfor.me</u> within seventy-two (72) hours of your sign-up letting us know that you are canceling your plan. After that, all payments are nonrefundable and there are no refunds or credits for partially used subscription periods. As mentioned above, following any cancellation, you will continue to have access to the Product through the end of your current term. We reserve the right to refuse refunds to anyone who abuses this Refund Policy.</p>
<p><i>Section 1.7 Authorized Payment Method.</i> You must keep a valid payment method on file with <u>Readitfor.me</u> LLC and its subsidiary products to pay for all fees. <u>Readitfor.me</u> LLC and its subsidiary products   will charge applicable Fees to any valid payment method that you authorize (“Authorized Payment Method”), and <u>Readitfor.me</u> LLC and its subsidiary products will continue to charge the Authorized Payment Method for applicable fees until this Agreement is terminated, and any and all outstanding fees have been paid in full.</p>
<p><strong>2.0 Duration and Cancellation of Promotional & Lifetime Offers</strong></p>
<p>For all Promotional Offers, the corresponding promotional period shall continue for the period as advertised. Unless you cancel a Promotional Offer before the end of the promotional period, you will automatically become a recurring subscriber to the type of <u>Readitfor.me</u> LLC and its subsidiary products service that you chose to sign up to under the Promotional Offer and the payment method you provided will automatically be charged the then-current price. If you cancel any Lifetime offer for during a promotional period or with seventy-two (72) hours of the original purchase, you will lose access to such service. </p>
<p><strong>3.0 License and Usage Rights</strong></p>
<p><strong>3.1 Usage of Course Materials:</strong> The course materials provided are exclusively for educational purposes. Any manufacturing, sharing, repurposing, or distribution of these materials without our express written consent is prohibited. Such consent is granted through a reseller license as part of the Simple Consultant program for use exclusively by Simple Consultants with an active subscription and only as prescribed. Unless a specific reseller license has been procured for a particular piece of content or material, you are not authorized to repurpose, sell, or distribute that material. </p>
<p><strong>3.2 Platform Content Distribution:</strong> If you have procured our platform with the intent to sell and distribute you content, you may only distribute content that you have either produced yourself or for which you have obtained explicit distribution rights through the Simple Consultant program. Our academy and course materials are intended solely for educational use. Unauthorized sale, repurposing, or distribution of this content is strictly forbidden. You may not create a competing AI platform, AI related certification program, consultancy or agency.</p>
<p><strong>3.3 AI Protocols and Tools Usage:</strong> Our AI protocols and tools, including but not limited to <u>Readitfor.me</u> and Simple protocols, training, and tools, are designed for individual usage. You are permitted to utilize any protocols, training and tools your organization has subscribed to for tasks within your organization. You may not host our tools or similar tools inspired by our tools and models on your own platform for customer facing, consulting or external use. Any resale, reverse engineering, consulting with, distribution, or repurposing of these protocols, training and tools is expressly prohibited.</p>
<p><strong>3.4 Certifications:</strong> Certificates, Certifications, Designations or other credentials granted may be tied to a given membership level or require continuing</p>
<p><strong>4.0 Recording and Distribution</strong></p>
<p>4.1 The Simple Licensee may deliver Simple-licensed content live or in a video conference using the medium of their choice. If a Simple licensee chooses to record any Simple-licensed content or its variants, the content must be hosted as protected content and may only be shared externally through the Simple platform. <i>Sharing a direct link to the hosted Simple content is prohibited.</i></p>
<p>4.2 To receive and maintain access to any recorded Simple-licensed content or its variants, the recipient’s organization must have at least one active paid seat on Simple Academy.</p>
<p><strong>5.0 Non-Disclosure Agreement (NDA)</strong></p>
<p>5.1 Confidentiality Obligation: As a user of <u>Readitfor.me</u> LLC and its subsidiary products, you may be exposed to confidential and proprietary information, including but not limited to business practices, strategies, customer data, and product details. You agree to keep this information confidential and not to disclose it to any third party without the express written consent of <u>Readitfor.me</u> LLC.</p>
<p>5.2 Permitted Disclosure: You may disclose confidential information only to employees or contractors who need to know such information in connection with their work for <u>Readitfor.me</u> LLC and its subsidiary products, and who are bound by written agreements with terms at least as protective as those in this section.</p>
<p>5.3 Duration of Confidentiality Obligation: Your duty to maintain the confidentiality of the information remains in effect even after the termination of your use of the products or services of <u>Readitfor.me</u> LLC and its subsidiary products.</p>
<p><strong>6.0 Contractor and Commission</strong></p>
<p>6.1 Only approved contractors are authorized to sell simple subscriptions under the then-current commission structure provided by Simple. Simple reserves the right to modify the commission structure and incentives at any time, unless explicitly agreed to as a part of a consultant relationship. Affiliates may request the current structure at any time. All commissions are contingent upon an active paid in full consultant or contractor subscription, where applicable. Simple reserves the right to terminate a relationship with a contractor as necessary.</p>
<p>6.2 The relationship established between Simple and all affiliates is that of independent contractors. Both parties shall conduct their respective businesses independently, bearing their own responsibilities and expenses, with no authority to incur obligations on behalf of the other unless explicitly stated herein. The term “consultant” is to be understood strictly as an independent contractor, not as a legal partner or affiliate.</p>
<p><strong>7.0 Non-Compete Agreement</strong></p>
<p>7.1 Non-Compete Covenant: For the duration of your subscription and for a period of Three years thereafter, you agree not to engage in or assist others in engaging in any business activity that is in direct competition with the principal business of <u>Readitfor.me</u> LLC, Simple Academy and its subsidiary products.</p>
<p>7.2 Scope and Limitation: The non-compete covenant is limited to the geographical area and scope of business in which <u>Readitfor.me</u> LLC and its subsidiary products operates. This agreement does not prohibit you from engaging in lawful business activities that are unrelated to the areas in which <u>Readitfor.me</u> LLC competes or from continuing activities you were engaged with prior to joining <u>Readitfor.me</u> or Simple.</p>
<p>7.3 Remedies for Breach: Violation of this non-compete agreement will entitle <u>Readitfor.me</u> LLC and its subsidiary products to seek injunctive relief, damages, and legal costs.</p>

<p><strong>8.0 Enforcement of Agreements</strong></p>
<p>8.1 Interpretation and Enforcement: These Non-Disclosure and Non-Compete agreements shall be interpreted in a manner that renders them valid and enforceable. If any provision is found unenforceable, it will be modified to the extent necessary to make it enforceable, and the rest of the agreement will remain in effect.</p>
<p>8.2 Governing Law: These agreements will be governed by and construed in accordance with the laws of Texas without regard to its conflict of laws principles.</p>
</div>
<div class="space4"></div>
<script type='text/javascript'>
</script>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/mod/footer.php') ?>